title: Config Overunder
apiEndpoint: /api/consul/config
queryParams:
  key: config/5etop-sports-overunder/data
fields:
  - fieldGroupClassName: row
    fieldGroup:
      - key: money_bet
        type: input
        className: col-md-3
        templateOptions:
          label: Money Bet
          type: number
